name: "Powertag Add-on"
version: "1.0.0"
slug: HA-powertagd
description: >-
  Runs Jlamas powertagd script
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: "services"
boot: "auto"
options:
  - name: USBPORT
    description: "USB Port for Powertag"
    default: "/dev/ttyUSB0"
    required: true
  - name: BROKER_IP
    description: "MQTT broker IP"
    default: "tcp://0.0.0.0:1883"
    required: true
  - name: USERNAME
    description: "Username for MQTT broker"
    default: "mqtt_user"
    required: true
  - name: PASSWORD
    description: "Password for MQTT broker"
    default: "mqtt_password"
    required: true
auto_uart: true
auto_update: true

